<div class="row page">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h3 class="title">AZervo</h3>
        <p class="text">Desenvolvido por <a
                    href="https://github.com/matheus-delazeri">Matheus Delazeri</a>
            e <a href="https://github.com/jpwsimao">João Pedro Simão</a>, o projeto teve origem no ano de 2022 como um
            trabalho do curso de Sistemas de Informação da UFSM.
        </p>
        <p class="text">Esta aplicação tem como principal intuito facilitar a busca por documentos digitais
            (internacionais e nacionais) para o público brasileiro, através de uma plataforma totalmente em Pt-Br e com
            uma interface simples.</p>
        <br>
        <h4 class="title">Fontes de Documentos</h4>
        <p>AZervo utiliza de algumas fontes de dados disponíveis na internet para disponibilzar os documentos. Sendo
            elas:</p>
        <ul>
            <li><a href="https://www.sci-hub.se/" class="title">Sci-Hub</a>: um dos maiores fornecedores de artigos
                digitais;
            </li>
        </ul>
        <p class="text">Além disso, o projeto contém uma base de dados particular que armazena os documentos das fontes
            listadas acima, em caso dos mesmos serem removidos destas.</p>
        <br>
        <h4 class="title">Termos de Uso</h4>
        <p class="text">Este documento alega que todo o conteúdo didático do site AZervo (<a
                    href="https://azervo.herokuapp.com/">https://azervo.herokuapp.com</a>) não é produzido e/ou
            distribuído pela AZervo. O presente
            termo, representado apenas pela AZervo, regulamenta apenas a realização da busca em bases de dados externas,
            sem vínculo algum com o projeto em questão.
            Não nos responsabilizamos com os conteúdos advindos destas fontes nem com a utilização dos conteúdos pelos
            usuários do site (visitantes).
            A permanência no site implica-se automaticamente na leitura e aceitação tácita do presente termos de uso.
        </p>
        <p class="text-black-50">Este termo foi atualizado pela última vez em 24 de outubro de 2022.</p>
    </div>
    <div class="col-md-3"></div>
</div>
