<?php
use App\AZervo;

AZervo::getModel("core");
?>
<div class="row page">
    <div class="col-md-2"></div>
    <form action="<?php echo AZervo::getUrl('user', 'login') ?>" method="post" class="col-md-8 container" style="align-items: center">
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">E-mail</span>
            </div>
            <input type="email" class="form-control" name="email" placeholder="Digite seu e-mail...">
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">Senha</span>
            </div>
            <input type="password" class="form-control" name="password" placeholder="Digite sua senha...">
        </div>
        <button type="submit" class="btn btn-dark" id="btn-login">
            Entrar
            <i class="fa fa-sign-in"></i>
        </button>
        <br>
        <p style="text-align: center">É novo por aqui? <a href="<?php echo AZervo::getUrl('user', 'register')?>">Registre-se!</a> </p>
    </form>
    <div class="col-md-2"></div>
</div>
