<?php

use App\AZervo;

$_user = AZervo::getModel('user')->userLoggedIn();
$_savedDocuments = AZervo::getModel('user')->getSavedDocuments();

?>
<div class="row page">
    <?php if ($_user): ?>
        <div class="col-md-2"></div>
        <div class="col-md-8" style="padding: 2% 0">
            <h3 class="title">Minha Conta</h3>
            <br>
            <?php
            echo "
                    <p><b>E-mail:</b> {$_user['email']}</p>
                    <p><b>Nome:</b> {$_user['name']}</p>
                ";
            ?>
            <br>
            <h3>Meus Documentos</h3>
            <br>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th style="width: 60%" scope="col">Documento</th>
                    <th style="width: 20%" scope="col">Links</th>
                    <th style="width: 20%" scope="col">Ações</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($_savedDocuments as $itemId => $id):
                    $document = AZervo::getModel("document")->load($id);
                    $links = "";
                    $count = 0;
                    foreach (explode(";", $document['links']) as $link) {
                        if($link == "") continue;
                        $count++;
                        $links .= "<li class='list-group-item'><a target='_blank' href='$link'>Link [$count]</a></li>";
                    }
                    ?>
                    <tr class='result' document='<?php echo $itemId ?>'>
                        <td>
                            <?php
                            foreach (AZervo::getModel('document')::ATTRIBUTES as $code => $label) {
                                echo "<p><b>$label:</b> {$document[$code]}</p>";
                            }
                            ?>
                        </td>
                        <td class='results-links'>
                            <ul class='list-group list-group-flush links-list'><?php echo $links?></ul>
                        </td>
                        <td class='actions'><i class='fa fa-trash unsave-document' document='<?php echo $id?>'></i></td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
        <div class="col-md-2"></div>

    <?php else: ?>
        <p>Faça login para acessar a sua conta.</p>
    <?php endif; ?>
</div>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        jQuery(document).on('click', '.unsave-document', function () {
            let $this = this
            let documentId = jQuery(this).attr('document')
            jQuery.ajax({
                url: '<?php echo AZervo::getUrl('user', 'unsaveDocument') ?>',
                method: 'POST',
                data: {
                    id: documentId,
                },
                success: function (data) {
                    jQuery($this).parent().parent().slideUp(150)
                }
            })
        })
    })
</script>