<?php
$_AZervo = new \App\AZervo();
?>
<head>
    <meta charset="UTF-8">
    <title>AZervo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="<?php echo $_AZervo->getSkinUrl("images/favicon.png")?>">
    <link rel="stylesheet" href="<?php echo $_AZervo->getSkinUrl("css/bootstrap/bootstrap.min.css")?>">
    <link rel="stylesheet" href="<?php echo $_AZervo->getSkinUrl("css/style.css")?>">
    <script src="<?php echo $_AZervo->getSkinUrl("js/jquery.min.js")?>"></script>
</head>