<?php
use App\AZervo;

?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>AZervo</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/x-icon" href="<?php echo AZervo::getSkinUrl("images/favicon.png")?>">
        <link rel="stylesheet" href="<?php echo AZervo::getSkinUrl("css/font-awesome/css/font-awesome.min.css")?>">
        <link rel="stylesheet" href="<?php echo AZervo::getSkinUrl("css/bootstrap/bootstrap.min.css")?>">
        <link rel="stylesheet" href="<?php echo AZervo::getSkinUrl("css/style.css")?>">
        <script src="<?php echo AZervo::getSkinUrl("js/jquery.min.js")?>"></script>
        <script src="<?php echo AZervo::getSkinUrl("js/popper.min.js")?>"></script>
        <script src="<?php echo AZervo::getSkinUrl("js/bootstrap.min.js")?>"></script>
        <script src="<?php echo AZervo::getSkinUrl("js/script.js")?>"></script>
    </head>
    <body>
    <?php AZervo::loadBlock('topHeader')?>
    <?php AZervo::displayMessages()?>

