<?php use App\AZervo; ?>

<div class="col-md-4" style="display: flex;flex-direction: column;justify-content: center; align-items: center">
    <img width="40%" src="<?php echo AZervo::getSkinUrl('images/not-found.png')?>" alt="">
    <br>
    <h5>Nenhum resultado encontrado...</h5>
    <br>
    <a href="<?php echo AZervo::getUrl('index')?>" type="button" class="btn btn-dark btn-search">Tentar novamente</a>
</div>