<?php
use App\AZervo;
$_isLoggedIn = isset($_SESSION["user_id"]);
?>
<div class="row top-header">
    <div class="col-md-3 col-sm-12">
        <a href="<?php echo AZervo::getUrl('index')?>">
            <img class="logo" src="<?php echo AZervo::getSkinUrl("images/logo.png") ?>" alt="">
        </a>
    </div>
    <div class="col-md-6"></div>
    <div class="col-md-3 top-menu" style="display: flex; align-items: center; justify-content: end">
        <a href="<?php echo AZervo::getUrl('index')?>">Início</a>
        <?php if($_isLoggedIn) {
            echo "<a href='".AZervo::getUrl('user', 'account')."'>Minha Conta</a>";
            echo "<a href='".AZervo::getUrl('user', 'logout')."'>Sair</a>";
        } else {
            echo "<a href='".AZervo::getUrl('user', 'account')."'>Entrar</a>";
        } ?>
        <a target="_blank" href="https://github.com/matheus-delazeri/AZervo">GitHub</a>
    </div>
</div>